version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - curl -v -s https://cloud-config.sa-dev.bb-fnds.com/dev/aws
  post_build:
    commands:
      - echo Build completed on `date`
